version: "3.8"
services:
  mongodb:
    image: mongo:5.0.2
    container_name: mongodb_database
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_CONTAINER_PORT
    volumes:
      - mongodb_database:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - preserve-info-network
  app:
    depends_on:
      - mongodb
    build: .
    container_name: preserve-info-api
    restart: unless-stopped
    env_file: .env
    ports:
      - $NODE_LOCAL_PORT:$NODE_CONTAINER_PORT
    environment:
      - DB_HOST=mongodb_database
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_CONTAINER_PORT
    stdin_open: true
    tty: true
    networks:
      - preserve-info-network
    volumes:
      - .:/usr/src/app
volumes:
  mongodb_database:
networks:
  preserve-info-network:
    driver: bridge
